version: '2'
services:
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    environment:
     MYSQL_ROOT_PASSWORD: redepp
     MYSQL_USER: root
     MYSQL_PASSWORD: redepp
  app:
     image: rails_dev
     command: bash -c "bundle install && service nginx restart && unicorn -c /unicorn/unicorn.rb -D"
     volumes:
          - /opt/dev/rails/boleto:/app
     ports:
          - "8080:80"
     tty  : true
     links:
          - mysql
     depends_on:
         - mysql
